### PR TITLE
Path: add drawPoints function

### PR DESCRIPTION
**Pull request by adrientetar**
To draw a Path contents into another class.

r? @devongovett

### CODE REVIEW

**Comment by Pomax** [comment]
small note: it would be useful to also see the documentation update in this PR, so it doesn't go out of sync =)

**Comment by adrientetar** [comment]
Seems travis failure is spurious.

**Comment by Pomax** [comment]
Also it looks to be failing for Node 4, which went out of active LTS in April of last year, and was dropped entirely in April of this year. Testing against it is actually a bad idea.

@devongovett it looks like the Node versions got out of sync with the LTS roadmap, testing against Node Stable, as well as v4 and v6, it's probably worth fixing that to stable, v6, and v8 (the current maintenance and active LTS versions respectively)

**Comment by devongovett** [comment]
I think this is equivalent to `path.toFunction()(ctx)`, and otherwise it's a very small utility function so not sure it's worth including here.

**Pull request closed without merging**
