### PR TITLE
[WIP] Add fk-shape util

### PR DESCRIPTION
**Pull request by khaledhosny**
Inspired by hb-shape and supports some of its features.

TODO:
* json output format.
* extend feature syntax.
* support more options.
* fk-view?

### CODE REVIEW

**Comment by devongovett** [comment]
Awesome, this is a good idea. See also #80 and https://github.com/OpenType/opentype-layout/issues/4. cc @twardoch

Something  similar to `hb-view` might also be neat, but there's the question of what it would render to. So far, I've rendered to SVG, Canvas, and PDF in different projects.

**Comment by khaledhosny** [comment]
I have something that outputs SVG, that I then manually pipe to rsvg-convert to rasterize or save to file and view.

**Comment by devongovett** [comment]
There is a [canvas](https://github.com/Automattic/node-canvas) implementation for Node on top of cairo as well.

**Comment by khaledhosny** [comment]
I found that one earlier, but since it depends on Cairo, the installation is a bit complex and I don’t think it is a dependency we want, but may be it can be made optional?

**Comment by khaledhosny** [comment]
Trying to finish the text serialization (and write a JSON one), the only information I’m missing is the mapping from glyph to input string index (HarfBuzz’s clusters), I’m not sure if FontKit keep such mapping and how to access it.

**Comment by devongovett** [comment]
fontkit doesn't currently track string indices, but I had started working on this a few weeks ago. See the [string-index](https://github.com/devongovett/fontkit/compare/string-index) branch. It doesn't quite work the same way as harfbuzz clusters (which are monotonic by default). Instead, it's a direct mapping of string indices for every glyph. It's a bit of a breaking change to the way glyphs are exposed though (no more `codePoints` array), which is why it isn't merged yet.

**Comment by khaledhosny** [comment]
I thought so. The `string-index` branch looks promising, anything I can help with?

**Pull request closed without merging**
